name: Build and Release App

on:
  push:
    branches: [ master ]

  workflow_dispatch:
  
permissions:
  contents: write


jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Build
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows
          
      - name: Create msix
        run: |
          mkdir exec
          flutter pub run msix:create -o exec -n "Secure Folder" --dont-install-certificate

      - name: Create zip
        run: |
          Rename-Item build\windows\runner\Release "Secure Folder"
          7z a exec "build\windows\runner\Secure Folder"
          
      - name: Create release
        uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Secure Folder
          tag_name: v0.0.1
          prerelease: true
          generate_release_notes: true
          files: exec/*
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: dhzdhd/SecureFolder
