name: Build and Release App

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Build
        run: |
          flutter pub get
          flutter build windows
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/runner/Release/

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
